apiVersion: apps/v1
kind: Deployment
metadata:
  name: templateservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templateservice
  template:
    metadata:
      labels:
        app: templateservice
    spec:
      containers:
        - name: templateservice
          image: DockerhubAccount/templateservice:latest
          env:
            - name: AppSettings__ConnectionString
              value: "data source=host.docker.internal;Database=DB;User ID=sa;Password=asdASD123"
---
apiVersion: v1
kind: Service
metadata:
  name: templateservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: templateservice
  ports:
    - name: templateservice
      protocol: TCP
      port: 80
      targetPort: 80
